bookers2/config/routes.rb
Rails.application.routes.draw do

 root to: "homes#top"
 get "/home/about" => "homes#about", as: "about"
 get "searches/search" => "searches#search", as: "search"
 devise_for :users

 resources :books, only:[:index, :show, :edit, :update, :create, :update, :destroy] do
  resource :book_comments, only:[:create, :destroy]
  resource :favorites, only:[:create, :destroy]
 end

 resources :users, only:[:index, :show, :edit, :update]
 resources :relationships, only: [:create, :destroy]
 resources :messages, only: [:create]
 resources :rooms, only: [:create,:show]
 get "relationships/followings/:id" => "relationships#followings", as: "followings"
 get "relationships/followers/:id" => "relationships#followers", as: "followers"
end

bookers2/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

bookers2/app/models/book.rb
class Book < ApplicationRecord
  is_impressionable counter_cache: true

  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true,
                   length: { maximum: 200 }

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def self.looks(searches, words)
    if searches == "perfect_match"
      @book = Book.where("title LIKE ?", "#{words}")
    elsif searches == "partial_match"
      @book = Book.where("title LIKE ?", "%#{words}%")
    elsif searches == "prefix_match"
      @book = Book.where("title LIKE ?", "#{words}%")
    else
      @book = Book.where("title LIKE ?", "%#{words}")
    end
  end

end

bookers2/app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates :comment, presence: true
end

bookers2/app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

bookers2/app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book
end

bookers2/app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
  validates :content, presence: true, length: { maximum: 140 }
end

bookers2/app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: 'User'

  validates :user_id, presence: true
  validates :follow_id, presence: true
end

bookers2/app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
end

bookers2/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  is_impressionable counter_cache: true

  has_many :books,dependent: :destroy
   attachment :profile_image
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_many :relationships, dependent: :destroy
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id', dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :user

  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy

   validates :name, uniqueness: true, on: :create
   validates :name, length: { in: 2..20 }
   validates :introduction, length: { maximum: 50 }

  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end

  def self.looks(searches, words)
    if searches == "perfect_match"
      @user = User.where("name LIKE ?", "#{words}")
    elsif searches == "partial_match"
      @user = User.where("name LIKE ?", "%#{words}%")
    elsif searches == "prefix_match"
      @user = User.where("name LIKE ?", "#{words}%")
    else
      @user = User.where("name LIKE ?", "%#{words}")
    end
  end

end

bookers2/app/controllers/books_controller.rb
class BooksController < ApplicationController
  impressionist :actions=> [:show]

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    @books = Book.all
    @user = current_user
     if @book.save
       flash[:notice] = "You have created book successfully."
       redirect_to book_path(@book)
     else
       render :index
     end
  end

  def index
    @users = User.all
    @user = current_user
    @book = Book.new
    books_all = Book.all.where(created_at: 1.week.ago.beginning_of_day..Time.zone.now.end_of_day)
    @books = books_all.includes(:favorites).sort {|a,b| b.favorites.size <=> a.favorites.size}
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @booknew = Book.new
    @book_comment = BookComment.new
    impressionist(@book, nil, unique: [:impressionable_id, :ip_address])
    @currentUserEntry=Entry.where(user_id: current_user.id)
    @userEntry=Entry.where(user_id: @user.id)
    unless @user.id == current_user.id
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id then
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      unless @isRoom
        @room = Room.new
        @entry = Entry.new
      end
    end
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user != current_user
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book)
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

bookers2/app/controllers/homes_controller.rb
class HomesController < ApplicationController
  
  def top
  end 
  
  def about
  end 
  
end

bookers2/app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!

  def create
    @room = Room.create
    @entry1 = Entry.create(:room_id => @room.id, :user_id => current_user.id)
    @entry2 = Entry.create(params.require(:entry).permit(:user_id, :room_id).merge(:room_id => @room.id))
    redirect_to "/rooms/#{@room.id}"
  end

  def show
    @room = Room.find(params[:id])
    if Entry.where(:user_id => current_user.id, :room_id => @room.id).present?
      @messages = @room.messages
      @message = Message.new
      @entries = @room.entries
      @user = User.find(params[:id])
    else
      redirect_back(fallback_location: root_path)
    end
  end
end

bookers2/app/helpers/application_helper.rb
module ApplicationHelper
end

bookers2/app/helpers/books_helper.rb
module BooksHelper
end

bookers2/app/helpers/favorites_helper.rb
module FavoritesHelper
end

bookers2/app/helpers/homes_helper.rb
module HomesHelper
end

bookers2/app/helpers/messages_helper.rb
module MessagesHelper
end

bookers2/app/helpers/rooms_helper.rb
module RoomsHelper
end

bookers2/app/helpers/searches_helper.rb
module SearchesHelper
end

bookers2/app/helpers/users_helper.rb
module UsersHelper
end

bookers2/app/views/layouts/_flash.html.erb
<%  flash.each do |key, value| %>
 <%= content_tag(:div, value, class: "flash flash__#{key}") %>
<% end %>

bookers2/app/views/layouts/_side_bar.html.erb
<% if @book.errors.any? %>
  <div class="error_messages_color">
    <h2><%= @book.errors.count %>error prohibited this obj from being saved:</h2>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </div>
<% end %>

<div class="profile mt-3">
  <h2>User info</h2>
  <%= attachment_image_tag user, :profile_image, :fill, 90, 90, format: 'jpeg', fallback: "no_image.jpg" %>
  <table class="table mt-3">
  <tr><th>name</th><th><%= user.name %></th></tr>
  <tr><th>introduction</th><th><%= user.introduction %></th></tr>
  <tr><th>follows</th><th><%= link_to followings_path(user.id) do %><%= user.followings.count %><% end %></th></tr>
  <tr><th>followers</th><th><%= link_to followers_path(user.id) do %><%= user.followers.count %><% end %></th></tr>
  </table>
</div>
   <% if user == current_user %>
    <%= link_to edit_user_path(user) do %>
      <div class="btn btn-outline-secondary btn-block  mt-2"><i class="fas fa-user-cog"></i></div>
    <% end %>
   <% else %>

    <% unless current_user == user %>
     <table>
       <tr>
         <td><% if current_user.following?(user) %>
                <%= form_for(current_user.relationships.find_by(follow_id: user.id), html: { method: :delete }) do |f| %>
                  <%= hidden_field_tag :follow_id, user.id %>
                  <%= f.submit 'フォローを外す', class: 'btn btn-info' %>
                <% end %>
              <% else %>
                <%= form_for(current_user.relationships.build) do |f| %>
                  <%= hidden_field_tag :follow_id, user.id %>
                  <%= f.submit 'フォローする', class: 'btn btn-info' %>
                <% end %>
               <% end %>
         </td><% end %>

         <td class="pl-3">
           <%if (current_user.following? @user) && (@user.following? current_user) %>
             <% if current_user.following?(user) %>
                <% if @isRoom == true %>
                 <a href="/rooms/<%= @roomId %>">chat</a>
                <% else %>
                  <%= form_for @room do |f| %>
                    <%= fields_for @entry do |e| %>
                      <%= e.hidden_field :user_id, :value=> @user.id %>
                    <% end %>
                    <%= f.submit "chatを始める" %>
                  <% end %>
                <% end %>
              <% end %>
           <% end %>
         </td>
       </tr>
     </table>

   <% end %>

<h2 class="mt-3">New book</h2>
<%= form_with model: book, local:true do |f| %>
  <h6>Title</h6>
  <%= f.text_field :title, class: "mb-2 form-control" %>
  <h6>Opinion</h6>
  <%= f.text_area :body, class: "form-control" %></br>
  <%= f.submit "Create Book", class: "mb-2 btn btn-success" %>

<% end %>

bookers2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css" integrity="sha384-SZXxX4whJ79/gErwcOYf+zWLeJdY/qpuqC4cAa9rOGUstPomtqpuNWT9wdPEn2fk" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>

  <header class="shadow-sm bg-dark">
    <nav class="navbar navbar-expand-lg navbar-dark">
      <div class="container">
        <a class="nav-link text-white" href="/"><h2>Bookers</h2></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
         <span class="navbar-toggler-icon"></span>
        </button>
         <div class="collapse navbar-collapse" id="navbarNavDropdown">
           <ul class="navbar-nav ml-auto">
             <% if user_signed_in? %>
               <li>
                 <%= link_to " Home", user_path(current_user), class: 'fas fa-home nav-link text-white' %> <!--ここのHomeと下のHomeではurlが違う事に注意。こっちはユーザーの投稿詳細画面-->
               </li>
               <li>
                 <%= link_to " Users", users_path, class: 'fas fa-users nav-link text-white' %>
               </li>
               <li>
                 <%= link_to " Books", books_path, class: 'fas fa-book-open nav-link text-white' %>
               </li>
               <li>
                 <%= link_to " logout", destroy_user_session_path, method: :delete, class: 'fas fa-sign-out-alt nav-link text-white' %>
               </li>
             <% else %>
               <li>
                 <%= link_to " Home", root_path, class: 'fas fa-home nav-link text-white' %>
               </li>
               <li>
                 <%= link_to " About", about_path, class: 'fas fa-link nav-link text-white' %>
               </li>
               <li>
                 <%= link_to " sign up", new_user_registration_path, class: 'fas fa-user-plus nav-link text-white' %>
               </li>
               <li>
                 <%= link_to " login", new_user_session_path, class: 'fas fa-sign-in-alt nav-link text-white' %>
               </li>
            <% end %>
          </div>
        </div>
     </nav>
  </header>
  <div class="container">
  <div class="row">
    <div class="col-md-7"></div>
      <div class="col-md-5 mt-3 mb-4">
       <% if user_signed_in? %>
        <%= form_with url: search_path, method: :get, local: :true do |f| %>
          <%= f.text_field :word %>
          <%= f.select :range, options_for_select([["User"], ["Book"]]) %>
          <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["部分一致","partial_match"],["前方一致","prefix_match"],["後方一致","Backward_match"]]) %>
          <%= f.submit "検索" %>
      　<% end %>
       <% end %>
      </div>
    </div>
  </div>

    <div class="notice"><%= render "layouts/flash" %></div>
    <%= yield %>

  <footer>
    <div class='container mt-5'>
      <div class='row'>
        <div class="col-12"><p class="text-center">CopyRight Infratop.inc</p></div>
      </div>
    </div>
  </footer>
  </body>
</html>