bookers2/config/routes.rb
Rails.application.routes.draw do

 root to: "homes#top"
 get "/home/about" => "homes#about", as: "about"
 get "searches/search" => "searches#search", as: "search"
 devise_for :users

 resources :books, only:[:index, :show, :edit, :update, :create, :update, :destroy] do
  resource :book_comments, only:[:create, :destroy]
  resource :favorites, only:[:create, :destroy]
 end

 resources :users, only:[:index, :show, :edit, :update]
 resources :relationships, only: [:create, :destroy]
 resources :messages, only: [:create]
 resources :rooms, only: [:create,:show]
 get "relationships/followings/:id" => "relationships#followings", as: "followings"
 get "relationships/followers/:id" => "relationships#followers", as: "followers"
end

bookers2/app/models/book.rb
class Book < ApplicationRecord
  is_impressionable counter_cache: true

  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true,
                   length: { maximum: 200 }

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def self.looks(searches, words)
    if searches == "perfect_match"
      @book = Book.where("title LIKE ?", "#{words}")
    elsif searches == "partial_match"
      @book = Book.where("title LIKE ?", "%#{words}%")
    elsif searches == "prefix_match"
      @book = Book.where("title LIKE ?", "#{words}%")
    else
      @book = Book.where("title LIKE ?", "%#{words}")
    end
  end

end

bookers2/app/controllers/books_controller.rb
class BooksController < ApplicationController
  impressionist :actions=> [:show]

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    @books = Book.all
    @user = current_user
     if @book.save
       flash[:notice] = "You have created book successfully."
       redirect_to book_path(@book)
     else
       render :index
     end
  end

  def index
    @users = User.all
    @user = current_user
    @book = Book.new
    books_all = Book.all.where(created_at: 1.week.ago.beginning_of_day..Time.zone.now.end_of_day)
    @books = books_all.includes(:favorites).sort {|a,b| b.favorites.size <=> a.favorites.size}
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @booknew = Book.new
    @book_comment = BookComment.new
    impressionist(@book, nil, unique: [:impressionable_id, :ip_address])
    @currentUserEntry=Entry.where(user_id: current_user.id)
    @userEntry=Entry.where(user_id: @user.id)
    unless @user.id == current_user.id
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id then
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      unless @isRoom
        @room = Room.new
        @entry = Entry.new
      end
    end
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user != current_user
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book)
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

bookers2/app/helpers/books_helper.rb
module BooksHelper
end

bookers2/app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1 class="mt-3">Editing Book</h1>

      <% if @book.errors.any? %>
        <div class="error_messages_color">
         <h2><%= @book.errors.count %>error prohibited this obj from being saved:</h2>
         <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
         <% end %>
        </div>
       <% end %>

      <%= form_with model:@book, local: true do |f| %>
        <h6>Title</h6>
        <%= f.text_field :title, class: "form-control mb-2" %>
        <h6>Opinion</h6>
        <%= f.text_area :body, class: "form-control" %></br>
        <%= f.submit 'Update Book', class: "btn btn-success mb-3" %>
      <% end %>

      <%= link_to "Show", book_path(@book) %>
       |
      <%= link_to "Back", books_path %>
    </div>
  </div>
</div>

bookers2/app/views/books/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render "layouts/side_bar", user: @user, book: @book %>
    </div>

    <div class="col-md-8 offset-md-1 mt-3">
       <h2>Books</h2>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th></th><!-- このthがtable bodyのユーザーイメージのカラムに対応する部分、　ここを空にしておくことでTitleのところがピッタリ揃う-->
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @books.each do |book| %>
              <tr>
                <td><%= link_to user_path(book.user) do %>
                <%= attachment_image_tag book.user, :profile_image, :fill, 90, 90, fallback: "no_image.jpg" %>
                <% end %></td>
                <td><%= link_to book_path(book) do %>
                    <%= book.title %><% end %></td>
                <td><%= book.body %></td>
                <td id="favorite-button_<%= book.id %>">
                  <%= render"favorites/favorite", book: book %>
                </td>
                <td>コメント数：<%= book.book_comments.count %></td>
                <td>閲覧数:<%= book.impressions_count %></td>
              </tr>
            <% end %>
          </tbody>
       </table>
     </div>
  </div>
</div>

bookers2/app/views/books/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render "layouts/side_bar", user: @user, book: @booknew %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2 class="mt-3">Book detail</h2>
      <table class="table">
        <tr>
          <tbody>
            <td class="text-center"><%= link_to user_path(@user) do %>
            <%= attachment_image_tag @user, :profile_image, :fill, 90, 90, fallback: "no_image.jpg" %></br>
            <%= @user.name %></td><% end %> <!-- book変数のuser_idに関連付けられているuserモデルのnameカラムを表示します -->
            <td><%= link_to book_path(@book) do %><%= @book.title %><% end %></td>
            <td><%= @book.body %></td>
            <td id="favorite-button_<%= @book.id %>">
              <%= render"favorites/favorite", book: @book %>
            </td>
            <td>閲覧数:<%= @book.impressions_count %></td>
            <% if @user == current_user %>
              <td><%= link_to "Edit", edit_book_path(@book), class: "btn btn-success" %></td>
              <td><%= link_to "Destroy", book_path(@book), method: :delete, class: "btn btn-danger" %></td>
            <% end %>
          </tbody>
        </tr>
      </table>
         <table id="comments_area">
          <%= render "book_comments/index", book: @book, user: @user %>
         </table>
          <%= render "book_comments/form", book: @book, book_comment: @book_comment %>
      </div>
    </div>
  </div>
</div>