bookers2/config/routes.rb
Rails.application.routes.draw do

 root to: "homes#top"
 get "/home/about" => "homes#about", as: "about"
 get "searches/search" => "searches#search", as: "search"
 devise_for :users

 resources :books, only:[:index, :show, :edit, :update, :create, :update, :destroy] do
  resource :book_comments, only:[:create, :destroy]
  resource :favorites, only:[:create, :destroy]
 end

 resources :users, only:[:index, :show, :edit, :update]
 resources :relationships, only: [:create, :destroy]
 resources :messages, only: [:create]
 resources :rooms, only: [:create,:show]
 get "relationships/followings/:id" => "relationships#followings", as: "followings"
 get "relationships/followers/:id" => "relationships#followers", as: "followers"
end

bookers2/app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book
end

bookers2/app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: @book.id)
    favorite.save
    #redirect_back(fallback_location: root_path)
  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy
    #redirect_back(fallback_location: root_path)
  end
end

bookers2/app/helpers/favorites_helper.rb
module FavoritesHelper
end

bookers2/app/views/favorites/_favorite.html.erb
<% if book.favorited_by?(current_user) %>
    <%= link_to book_favorites_path(book),'data-turbolinks': false, method: :delete, class: "favorite-color", remote: true do %>
      ♥<%= book.favorites.count %>
    <% end %>
<% else %>
    <%= link_to book_favorites_path(book),'data-turbolinks': false, method: :post, remote: true do %>
      ♡<%= book.favorites.count %>
    <% end %>
<% end %>

bookers2/app/views/favorites/create.js.erb
$("#favorite-button_<%= @book.id %>").html("<%= j(render 'favorite', book: @book ) %>");

bookers2/app/views/favorites/destroy.js.erb
$("#favorite-button_<%= @book.id %>").html("<%= j(render 'favorite', book: @book ) %>");