bookers2/config/routes.rb
Rails.application.routes.draw do

 root to: "homes#top"
 get "/home/about" => "homes#about", as: "about"
 get "searches/search" => "searches#search", as: "search"
 devise_for :users

 resources :books, only:[:index, :show, :edit, :update, :create, :update, :destroy] do
  resource :book_comments, only:[:create, :destroy]
  resource :favorites, only:[:create, :destroy]
 end

 resources :users, only:[:index, :show, :edit, :update]
 resources :relationships, only: [:create, :destroy]
 resources :messages, only: [:create]
 resources :rooms, only: [:create,:show]
 get "relationships/followings/:id" => "relationships#followings", as: "followings"
 get "relationships/followers/:id" => "relationships#followers", as: "followers"
end

bookers2/app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def search
    title= params[:range]
    search = params[:word]
    @output = "#{title} search for \"#{search}\""
    @range = params[:range]
    if @range == "User"
      @users = User.looks(params[:search], params[:word])
    elsif @range == "Book"
      @books = Book.looks(params[:search], params[:word])
    end
  end
end

bookers2/app/helpers/searches_helper.rb
module SearchesHelper
end

bookers2/app/views/searches/search.html.erb
<div class="container">
  <div class="row">
   <h2><%= @output %></h2>
    <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <% if @range == "User" %>
                <th>image</th>
                <th>name</th>
              <% else %>
                <th>title</th>
                <th>body</th>
              <% end %>
              <th></th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% if @range == "User" %>
               <% @users.each do |user| %>
                <tr>
                  <td><%= attachment_image_tag user, :profile_image, :fill, 90, 90, fallback: "no_image.jpg" %></td>
                  <td><%= user.name %></td>
                  <td><%= link_to "Show", user_path(user) %></td>
                </tr>
               <% end %>
            <% else %>
               <% @books.each do |book| %>
                 <tr>
                  <td><%= link_to user_path(book.user) do %>
                  <%= attachment_image_tag book.user, :profile_image, :fill, 90, 90, fallback: "no_image.jpg" %>
                  <% end %></td>
                  <td><%= link_to book_path(book) do %>
                      <%= book.title %><% end %></td>
                  <td><%= book.body %></td>
                 </tr>
               <% end %>
            <% end %>
          </tbody>
    </table>
  </div>
</div>